# -*- coding: utf-8 -*-
"""ML_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-fNpnESPW60Ygr5HBg5uniX_Nbs1j0l

Kaggle Source: https://www.kaggle.com/datasets/mahmoudelhemaly/students-grading-dataset/data
"""

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('Students Performance Dataset.csv')

print("Dataset loaded successfully!")
print(df.shape)
df.head()

import os
print(os.listdir())

"""### Milestone 1: Data Pipeline

#### Step 1 — Load & Explore the Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('Students Performance Dataset.csv')

# Deduplication
initial_shape = df.shape
df = df.drop_duplicates()
print(f"Removed {initial_shape[0] - df.shape[0]} duplicate rows.")

# Basic exploration
print("Shape after deduplication:", df.shape)
display(df.head())

"""#### Step 2 — Handle Missing Values"""

# Check missing percentage
missing = df.isnull().sum() / len(df) * 100
print("Missing Percentage:\n", missing[missing > 0])

# For numerical columns → fill with median
if 'Age' in df.columns:
    df['Age'] = df['Age'].fillna(df['Age'].median())

# For categorical columns → fill with mode
if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

# Drop columns with >50% missing
df.dropna(thresh=len(df)*0.5, axis=1, inplace=True)

"""#### Step 3 — Drop Irrelevant Columns"""

# Drop ID/name columns — not useful for ML
df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email'],
        inplace=True, errors='ignore')

"""#### Step 4 — Handle Outliers"""

# Visualize outliers with boxplot
if 'Total_Score' in df.columns:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df['Total_Score'])
    plt.title('Boxplot of Total_Score')
    plt.show()

    # Remove outliers using IQR method
    Q1 = df['Total_Score'].quantile(0.25)
    Q3 = df['Total_Score'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df['Total_Score'] >= lower_bound) & (df['Total_Score'] <= upper_bound)]

"""#### Step 5 — Encode Categorical Variables"""

from sklearn.preprocessing import LabelEncoder

# Label encoding for binary columns
if 'Gender' in df.columns:
    le = LabelEncoder()
    df['Gender'] = le.fit_transform(df['Gender'].astype(str))

# Ordinal Encoding for Grade (preserves order)
grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
if 'Grade' in df.columns:
    df['Grade'] = df['Grade'].map(grade_map)

# One-hot encoding for multi-category columns
cats_to_encode = [col for col in ['Department'] if col in df.columns]
df = pd.get_dummies(df, columns=cats_to_encode, drop_first=True)

"""#### Step 6 — Normalize Numerical Features"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define features and target
# Assuming 'Grade' is our target based on your summary
if 'Grade' in df.columns:
    X = df.drop(columns=['Grade'])
    y = df['Grade']

    # Train-Test Split (80/20 Stratified)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    # Scaling (Fit on Train only to prevent data leakage)
    scaler = StandardScaler()
    num_cols = X_train.select_dtypes(include=['float64', 'int64']).columns

    X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
    X_test[num_cols] = scaler.transform(X_test[num_cols])

    print("Data split and scaled successfully.")
    print(f"Training set shape: {X_train.shape}")
else:
    print("Target column 'Grade' not found.")

"""#### Step 7 — Visualizations"""

# 1. Grade distribution (Note: column names might have changed due to dummy encoding)
# Re-loading or using a copy for categorical plots if necessary,
# or plotting specific dummy columns.

# 2. Correlation heatmap
plt.figure(figsize=(12, 8))
# Added numeric_only=True to fix the ValueError with string columns
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

# 3. Attendance vs Score
attendance_col = 'Attendance (%)'
if attendance_col in df.columns and 'Total_Score' in df.columns:
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=attendance_col, y='Total_Score', data=df)
    plt.title('Attendance vs Total Score')
    plt.show()

"""## Milestone 2: Model Selection

####Step 1 - Model Import
"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

"""#### Step 2 - Remove Data Leakage Feature"""

if 'Total_Score' in X_train.columns:
    X_train = X_train.drop(columns=['Total_Score'])
    X_test = X_test.drop(columns=['Total_Score'])

print("Removed Total_Score to prevent data leakage.")

"""#### Step 3 - Model Architecture"""

# 🔹 Model 1: Random Forest (Primary Model - Baseline)
# Why: Handles mixed data types, missing values, and non-linear interactions well
rf_model = RandomForestClassifier(
    n_estimators=200,      # increased trees for better stability
    max_depth=12,          # controlled depth to reduce overfitting
    min_samples_split=5,   # prevents overfitting on small splits
    random_state=42
)

# 🔹 Model 2: XGBoost (Advanced Gradient Boosting Model)
# Why: Best suited for structured/tabular data with complex feature interactions
xgb_model = XGBClassifier(
    n_estimators=300,      # increased boosting rounds for better learning
    learning_rate=0.1,
    max_depth=6,           # balanced depth (controls overfitting vs learning power)
    subsample=0.8,         # improves generalization
    colsample_bytree=0.8,  # reduces overfitting by feature sampling
    random_state=42,
    eval_metric='mlogloss'
)

print("\n=== Model Architectures ===")
print("\nRandom Forest Model:\n", rf_model)
print("\nXGBoost Model:\n", xgb_model)

"""#### Step 4 - Feature Overview"""

print("\nNumber of features used:", X_train.shape[1])
print("Sample feature names:\n", list(X_train.columns)[:10])