# -*- coding: utf-8 -*-
"""ML_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brL_M8GwYUakhgga-opwoMYmwdd9N3KU

Kaggle Source: https://www.kaggle.com/datasets/mahmoudelhemaly/students-grading-dataset/data
"""

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('Students Performance Dataset.csv')

print("Dataset loaded successfully!")
print(df.shape)
df.head()

import os
print(os.listdir())

"""### Milestone 1: Data Pipeline

#### Step 1 — Load & Explore the Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('Students Performance Dataset.csv')

# Deduplication
initial_shape = df.shape
df = df.drop_duplicates()
print(f"Removed {initial_shape[0] - df.shape[0]} duplicate rows.")

# Basic exploration
print("Shape after deduplication:", df.shape)
display(df.head())

"""#### Step 2 — Handle Missing Values"""

# Check missing percentage
missing = df.isnull().sum() / len(df) * 100
print("Missing Percentage:\n", missing[missing > 0])

# For numerical columns → fill with median
if 'Age' in df.columns:
    df['Age'] = df['Age'].fillna(df['Age'].median())

# For categorical columns → fill with mode
if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

# Drop columns with >50% missing
df.dropna(thresh=len(df)*0.5, axis=1, inplace=True)

"""#### Step 3 — Drop Irrelevant Columns"""

# Drop ID/name columns — not useful for ML
df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email'],
        inplace=True, errors='ignore')

"""#### Step 4 — Handle Outliers"""

# Visualize outliers with boxplot
if 'Total_Score' in df.columns:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df['Total_Score'])
    plt.title('Boxplot of Total_Score')
    plt.show()

    # Remove outliers using IQR method
    Q1 = df['Total_Score'].quantile(0.25)
    Q3 = df['Total_Score'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df['Total_Score'] >= lower_bound) & (df['Total_Score'] <= upper_bound)]

"""#### Step 5 — Encode Categorical Variables"""

from sklearn.preprocessing import LabelEncoder

# Label encoding for binary columns
if 'Gender' in df.columns:
    le = LabelEncoder()
    df['Gender'] = le.fit_transform(df['Gender'].astype(str))

# Ordinal Encoding for Grade (preserves order)
grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
if 'Grade' in df.columns:
    df['Grade'] = df['Grade'].map(grade_map)

# One-hot encoding for multi-category columns
cats_to_encode = [col for col in ['Department'] if col in df.columns]
df = pd.get_dummies(df, columns=cats_to_encode, drop_first=True)

"""#### Step 6 — Normalize Numerical Features"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define features and target
# Assuming 'Grade' is our target based on your summary
if 'Grade' in df.columns:
    X = df.drop(columns=['Grade'])
    y = df['Grade']

    # Train-Test Split (80/20 Stratified)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    # Scaling (Fit on Train only to prevent data leakage)
    scaler = StandardScaler()
    num_cols = X_train.select_dtypes(include=['float64', 'int64']).columns

    X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
    X_test[num_cols] = scaler.transform(X_test[num_cols])

    print("Data split and scaled successfully.")
    print(f"Training set shape: {X_train.shape}")
else:
    print("Target column 'Grade' not found.")

"""#### Step 7 — Visualizations"""

# 1. Grade distribution (Note: column names might have changed due to dummy encoding)
# Re-loading or using a copy for categorical plots if necessary,
# or plotting specific dummy columns.

# 2. Correlation heatmap
plt.figure(figsize=(12, 8))
# Added numeric_only=True to fix the ValueError with string columns
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

# 3. Attendance vs Score
# Note: 'Attendance (%)' is the correct column name based on previous exploration
attendance_col = 'Attendance (%)'
if attendance_col in df.columns and 'Total_Score' in df.columns:
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=attendance_col, y='Total_Score', data=df)
    plt.title('Attendance vs Total Score')
    plt.show()

"""## Milestone 2: Model Selection

####Step 1 - Model Import
"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

"""#### Step 2 - Remove Data Leakage Feature"""

if 'Total_Score' in X_train.columns:
    X_train = X_train.drop(columns=['Total_Score'])
    X_test = X_test.drop(columns=['Total_Score'])

print("Removed Total_Score to prevent data leakage.")

"""#### Step 3 - Model Architecture"""

# 🔹 Model 1: Random Forest (Primary Model - Baseline)
# Why: Handles mixed data types, missing values, and non-linear interactions well
rf_model = RandomForestClassifier(
    n_estimators=200,      # increased trees for better stability
    max_depth=12,          # controlled depth to reduce overfitting
    min_samples_split=5,   # prevents overfitting on small splits
    random_state=42
)

# 🔹 Model 2: XGBoost (Advanced Gradient Boosting Model)
# Why: Best suited for structured/tabular data with complex feature interactions
xgb_model = XGBClassifier(
    n_estimators=300,      # increased boosting rounds for better learning
    learning_rate=0.1,
    max_depth=6,           # balanced depth (controls overfitting vs learning power)
    subsample=0.8,         # improves generalization
    colsample_bytree=0.8,  # reduces overfitting by feature sampling
    random_state=42,
    eval_metric='mlogloss'
)

print("\n=== Model Architectures ===")
print("\nRandom Forest Model:\n", rf_model)
print("\nXGBoost Model:\n", xgb_model)

"""#### Step 4 - Feature Overview"""

print("\nNumber of features used:", X_train.shape[1])
print("Sample feature names:\n", list(X_train.columns)[:10])

"""## Milestone 3: The Training Loop

### Step 1 - Data Splitting (Train, Validation, Test)
"""

from google.colab import files
import pandas as pd
import io
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 1. Upload the file
print("Please upload 'Students Performance Dataset.csv'")
uploaded = files.upload()

# 2. Process and Split
for filename in uploaded.keys():
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
    print(f"Successfully loaded: {filename}")

    # Preprocessing
    df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email'], inplace=True, errors='ignore')

    # Encode all object/categorical columns automatically
    le = LabelEncoder()
    for col in df.select_dtypes(include=['object']).columns:
        if col != 'Grade':
            df[col] = le.fit_transform(df[col].astype(str))

    grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
    if 'Grade' in df.columns:
        df['Grade'] = df['Grade'].map(grade_map)

X = df.drop(columns=['Grade'])
y = df['Grade']

# Split 1: Train/Test (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Remove data leakage
if 'Total_Score' in X_train.columns:
    X_train = X_train.drop(columns=['Total_Score'])
    X_test = X_test.drop(columns=['Total_Score'])

# Split 2: Train/Validation (80/20 from training set)
X_train_final, X_val, y_train_final, y_val = train_test_split(X_train, y_train, test_size=0.20, random_state=42, stratify=y_train)

print("\nData split into training, validation, and test sets successfully.")
print(f"Final Training set shape: {X_train_final.shape}")
print(f"Validation set shape: {X_val.shape}")
print(f"Test set shape: {X_test.shape}")

"""### Step 2 - Training Procedure and Performance Evaluation

In this section, we feed our features (Attendance, Scores, Study Hours, etc.) into our models to predict the student grades. We evaluate performance on both the **Training Set** and the **Validation Set** to ensure the model is learning patterns without just memorizing the data (overfitting).
"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

# --- 1. Model Initialization ---
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_split=5,
    random_state=42
)

xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='mlogloss'
)

# --- 2. Random Forest Training ---
print("Training Random Forest...")
rf_model.fit(X_train_final, y_train_final)

# Predictions
rf_train_preds = rf_model.predict(X_train_final)
rf_val_preds = rf_model.predict(X_val)

# Results
print("\n--- Random Forest Results ---")
print(f"Training Accuracy: {accuracy_score(y_train_final, rf_train_preds):.4f}")
print(f"Validation Accuracy: {accuracy_score(y_val, rf_val_preds):.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, rf_val_preds))

# --- 3. XGBoost Training ---
print("\nTraining XGBoost...")
xgb_model.fit(
    X_train_final, y_train_final,
    eval_set=[(X_train_final, y_train_final), (X_val, y_val)],
    verbose=False
)

# Predictions
xgb_train_preds = xgb_model.predict(X_train_final)
xgb_val_preds = xgb_model.predict(X_val)

# Results
print("\n--- XGBoost Results ---")
print(f"Training Accuracy: {accuracy_score(y_train_final, xgb_train_preds):.4f}")
print(f"Validation Accuracy: {accuracy_score(y_val, xgb_val_preds):.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, xgb_val_preds))

"""### Step 3: Training Results & Observations

To visualize the training behavior of the XGBoost model, we plot the **Log Loss** for both training and validation sets. This allows us to see if the error is decreasing consistently or if the validation error starts to rise (a sign of overfitting).
"""

# Retrieve performance metrics
results = xgb_model.evals_result()
epochs = len(results['validation_0']['mlogloss'])
x_axis = range(0, epochs)

# Plot Log Loss
plt.figure(figsize=(10, 6))
plt.plot(x_axis, results['validation_0']['mlogloss'], label='Train')
plt.plot(x_axis, results['validation_1']['mlogloss'], label='Validation')
plt.legend()
plt.ylabel('Log Loss')
plt.xlabel('Iterations')
plt.title('XGBoost Learning Curve (Training vs Validation Loss)')
plt.show()

"""### Step 3.1: Random Forest Training Behavior

For Random Forest, we can visualize the 'Learning Curve' by looking at how the validation accuracy stabilizes as we increase the number of trees (n_estimators). This helps us confirm if 200 trees were sufficient for the model to converge.
"""

from sklearn.model_selection import validation_curve
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt

# Define the range of trees to test
param_range = [10, 50, 100, 150, 200]

train_scores, test_scores = validation_curve(
    RandomForestClassifier(max_depth=12, min_samples_split=5, random_state=42),
    X_train_final, y_train_final,
    param_name="n_estimators",
    param_range=param_range,
    cv=3,
    scoring="accuracy",
    n_jobs=-1
)

# Calculate mean and standard deviation
train_mean = np.mean(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)

# Plot Random Forest Learning Curve
plt.figure(figsize=(10, 6))
plt.plot(param_range, train_mean, label="Training Score", color="blue", marker='o')
plt.plot(param_range, test_mean, label="Cross-Validation Score", color="green", marker='o')
plt.title("Random Forest Learning Curve (Trees vs Accuracy)")
plt.xlabel("Number of Trees (n_estimators)")
plt.ylabel("Accuracy")
plt.legend(loc="best")
plt.grid(True)
plt.show()