# -*- coding: utf-8 -*-
"""ml 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qy9MIMyvduUVAwfbkJyZ98CSmL2is1wN

Kaggle Source: https://www.kaggle.com/datasets/mahmoudelhemaly/students-grading-dataset/data
"""

!pip install xgboost
!pip install scikit-learn
!pip install pandas
!pip install matplotlib
!pip install seaborn

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('Students Performance Dataset.csv')

print("Dataset loaded successfully!")
print(df.shape)
df.head()

import os
print(os.listdir())

"""Milestone 1: Data Pipeline
Step 1 — Load & Explore the Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('Students Performance Dataset.csv')

# Deduplication
initial_shape = df.shape
df = df.drop_duplicates()
print(f"Removed {initial_shape[0] - df.shape[0]} duplicate rows.")

# Basic exploration
print("Shape after deduplication:", df.shape)
display(df.head())

"""Step 2 — Handle Missing Values"""

# Check missing percentage
missing = df.isnull().sum() / len(df) * 100
print("Missing Percentage:\n", missing[missing > 0])

# For numerical columns → fill with median
if 'Age' in df.columns:
    df['Age'] = df['Age'].fillna(df['Age'].median())

# For categorical columns → fill with mode
if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

# Drop columns with >50% missing
df.dropna(thresh=len(df)*0.5, axis=1, inplace=True)

"""Step 3 — Drop Irrelevant Columns"""

# Drop ID/name columns — not useful for ML
df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email'],
        inplace=True, errors='ignore')

"""#### Step 4 — Handle Outliers

"""

# Visualize outliers with boxplot
if 'Total_Score' in df.columns:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df['Total_Score'])
    plt.title('Boxplot of Total_Score')
    plt.show()

    # Remove outliers using IQR method
    Q1 = df['Total_Score'].quantile(0.25)
    Q3 = df['Total_Score'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df['Total_Score'] >= lower_bound) & (df['Total_Score'] <= upper_bound)]

"""#### Step 5 — Encode Categorical Variables

"""

from sklearn.preprocessing import LabelEncoder

# Label encoding for binary columns
if 'Gender' in df.columns:
    le = LabelEncoder()
    df['Gender'] = le.fit_transform(df['Gender'].astype(str))

# Ordinal Encoding for Grade (preserves order)
grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
if 'Grade' in df.columns:
    df['Grade'] = df['Grade'].map(grade_map)

# One-hot encoding for multi-category columns
cats_to_encode = [col for col in ['Department'] if col in df.columns]
df = pd.get_dummies(df, columns=cats_to_encode, drop_first=True)

"""Step 6 — Normalize Numerical Features"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define features and target
# Assuming 'Grade' is our target based on your summary
if 'Grade' in df.columns:
    X = df.drop(columns=['Grade'])
    y = df['Grade']

    # Train-Test Split (80/20 Stratified)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    # Scaling (Fit on Train only to prevent data leakage)
    scaler = StandardScaler()
    num_cols = X_train.select_dtypes(include=['float64', 'int64']).columns

    X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
    X_test[num_cols] = scaler.transform(X_test[num_cols])

    print("Data split and scaled successfully.")
    print(f"Training set shape: {X_train.shape}")
else:
    print("Target column 'Grade' not found.")

"""Step 7 — Visualizations"""

# 1. Grade distribution (Note: column names might have changed due to dummy encoding)
# Re-loading or using a copy for categorical plots if necessary,
# or plotting specific dummy columns.

# 2. Correlation heatmap
plt.figure(figsize=(12, 8))
# Added numeric_only=True to fix the ValueError with string columns
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

# 3. Attendance vs Score
# Note: 'Attendance (%)' is the correct column name based on previous exploration
attendance_col = 'Attendance (%)'
if attendance_col in df.columns and 'Total_Score' in df.columns:
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=attendance_col, y='Total_Score', data=df)
    plt.title('Attendance vs Total Score')
    plt.show()

"""Milestone 2: Model Selection

Step 1 - Model Import
"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

"""Step 2 - Remove Data Leakage Feature"""

if 'Total_Score' in X_train.columns:
    X_train = X_train.drop(columns=['Total_Score'])
    X_test = X_test.drop(columns=['Total_Score'])

print("Removed Total_Score to prevent data leakage.")

"""Step 3 - Model Architecture"""

# 🔹 Model 1: Random Forest (Primary Model - Baseline)
# Why: Handles mixed data types, missing values, and non-linear interactions well
rf_model = RandomForestClassifier(
    n_estimators=200,      # increased trees for better stability
    max_depth=12,          # controlled depth to reduce overfitting
    min_samples_split=5,   # prevents overfitting on small splits
    random_state=42
)

# 🔹 Model 2: XGBoost (Advanced Gradient Boosting Model)
# Why: Best suited for structured/tabular data with complex feature interactions
xgb_model = XGBClassifier(
    n_estimators=300,      # increased boosting rounds for better learning
    learning_rate=0.1,
    max_depth=6,           # balanced depth (controls overfitting vs learning power)
    subsample=0.8,         # improves generalization
    colsample_bytree=0.8,  # reduces overfitting by feature sampling
    random_state=42,
    eval_metric='mlogloss'
)

print("\n=== Model Architectures ===")
print("\nRandom Forest Model:\n", rf_model)
print("\nXGBoost Model:\n", xgb_model)

"""Step 4 - Feature Overview"""

print("\nNumber of features used:", X_train.shape[1])
print("Sample feature names:\n", list(X_train.columns)[:10])

"""Milestone 3: The Training Loop

Step 1 - Data Splitting (Train, Validation, Test)
"""

from google.colab import files
import pandas as pd
import io
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 1. Upload the file
print("Please upload 'Students Performance Dataset.csv'")
uploaded = files.upload()

# 2. Process and Split
for filename in uploaded.keys():
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
    print(f"Successfully loaded: {filename}")

    # Preprocessing
    df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email'], inplace=True, errors='ignore')

    # Encode all object/categorical columns automatically
    le = LabelEncoder()
    for col in df.select_dtypes(include=['object']).columns:
        if col != 'Grade':
            df[col] = le.fit_transform(df[col].astype(str))

    grade_map = {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}
    if 'Grade' in df.columns:
        df['Grade'] = df['Grade'].map(grade_map)

X = df.drop(columns=['Grade'])
y = df['Grade']

# Split 1: Train/Test (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Remove data leakage
if 'Total_Score' in X_train.columns:
    X_train = X_train.drop(columns=['Total_Score'])
    X_test = X_test.drop(columns=['Total_Score'])

# Split 2: Train/Validation (80/20 from training set)
X_train_final, X_val, y_train_final, y_val = train_test_split(X_train, y_train, test_size=0.20, random_state=42, stratify=y_train)

print("\nData split into training, validation, and test sets successfully.")
print(f"Final Training set shape: {X_train_final.shape}")
print(f"Validation set shape: {X_val.shape}")
print(f"Test set shape: {X_test.shape}")

"""Step 2 - Training Procedure and Performance Evaluation
In this section, we feed our features (Attendance, Scores, Study Hours, etc.) into our models to predict the student grades. We evaluate performance on both the Training Set and the Validation Set to ensure the model is learning patterns without just memorizing the data (overfitting).
"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

# --- 1. Model Initialization ---
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_split=5,
    random_state=42
)

xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='mlogloss'
)

# --- 2. Random Forest Training ---
print("Training Random Forest...")
rf_model.fit(X_train_final, y_train_final)

# Predictions
rf_train_preds = rf_model.predict(X_train_final)
rf_val_preds = rf_model.predict(X_val)

# Results
print("\n--- Random Forest Results ---")
print(f"Training Accuracy: {accuracy_score(y_train_final, rf_train_preds):.4f}")
print(f"Validation Accuracy: {accuracy_score(y_val, rf_val_preds):.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, rf_val_preds))

# --- 3. XGBoost Training ---
print("\nTraining XGBoost...")
xgb_model.fit(
    X_train_final, y_train_final,
    eval_set=[(X_train_final, y_train_final), (X_val, y_val)],
    verbose=False
)

# Predictions
xgb_train_preds = xgb_model.predict(X_train_final)
xgb_val_preds = xgb_model.predict(X_val)

# Results
print("\n--- XGBoost Results ---")
print(f"Training Accuracy: {accuracy_score(y_train_final, xgb_train_preds):.4f}")
print(f"Validation Accuracy: {accuracy_score(y_val, xgb_val_preds):.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, xgb_val_preds))

"""Step 3: Training Results & Observations
To visualize the training behavior of the XGBoost model, we plot the Log Loss for both training and validation sets. This allows us to see if the error is decreasing consistently or if the validation error starts to rise (a sign of overfitting).
"""

# Retrieve performance metrics
results = xgb_model.evals_result()
epochs = len(results['validation_0']['mlogloss'])
x_axis = range(0, epochs)

# Plot Log Loss
plt.figure(figsize=(10, 6))
plt.plot(x_axis, results['validation_0']['mlogloss'], label='Train')
plt.plot(x_axis, results['validation_1']['mlogloss'], label='Validation')
plt.legend()
plt.ylabel('Log Loss')
plt.xlabel('Iterations')
plt.title('XGBoost Learning Curve (Training vs Validation Loss)')
plt.show()

"""Step 3.1: Random Forest Training Behavior
For Random Forest, we can visualize the 'Learning Curve' by looking at how the validation accuracy stabilizes as we increase the number of trees (n_estimators). This helps us confirm if 200 trees were sufficient for the model to converge.
"""

from sklearn.model_selection import validation_curve
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt

# Define the range of trees to test
param_range = [10, 50, 100, 150, 200]

train_scores, test_scores = validation_curve(
    RandomForestClassifier(max_depth=12, min_samples_split=5, random_state=42),
    X_train_final, y_train_final,
    param_name="n_estimators",
    param_range=param_range,
    cv=3,
    scoring="accuracy",
    n_jobs=-1
)

# Calculate mean and standard deviation
train_mean = np.mean(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)

# Plot Random Forest Learning Curve
plt.figure(figsize=(10, 6))
plt.plot(param_range, train_mean, label="Training Score", color="blue", marker='o')
plt.plot(param_range, test_mean, label="Cross-Validation Score", color="green", marker='o')
plt.title("Random Forest Learning Curve (Trees vs Accuracy)")
plt.xlabel("Number of Trees (n_estimators)")
plt.ylabel("Accuracy")
plt.legend(loc="best")
plt.grid(True)
plt.show()

"""Milestone 4: Model Optimization

Step 1 - Define the Problem

From Milestone 3,

Training Accuracy > Validation Accuracy
Gap = overfitting
Ways to fix it:

Grid Search
Stronger Regularisation
Validation-based Selection
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report
from xgboost import XGBClassifier

"""Step 1 - Baseline Evaluation"""

print("=" * 55)
print("        STEP 1 — BASELINE MODEL EVALUATION")
print("=" * 55)

# --- Random Forest Baseline ---
rf_base = RandomForestClassifier(random_state=42)
rf_base.fit(X_train_final, y_train_final)

rf_train_preds = rf_base.predict(X_train_final)
rf_val_preds   = rf_base.predict(X_val)

rf_train_acc = accuracy_score(y_train_final, rf_train_preds)
rf_val_acc   = accuracy_score(y_val, rf_val_preds)
rf_gap       = rf_train_acc - rf_val_acc

print("\n=== Baseline Random Forest ===")
print(f"Training Accuracy:   {rf_train_acc:.4f}")
print(f"Validation Accuracy: {rf_val_acc:.4f}")
print(f"Overfitting Gap:     {rf_gap:.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, rf_val_preds, target_names=['F','D','C','B','A']))

# --- XGBoost Baseline ---
xgb_base = XGBClassifier(random_state=42, eval_metric='mlogloss')
xgb_base.fit(X_train_final, y_train_final)

xgb_train_preds = xgb_base.predict(X_train_final)
xgb_val_preds   = xgb_base.predict(X_val)

xgb_train_acc = accuracy_score(y_train_final, xgb_train_preds)
xgb_val_acc   = accuracy_score(y_val, xgb_val_preds)
xgb_gap       = xgb_train_acc - xgb_val_acc

print("\n=== Baseline XGBoost ===")
print(f"Training Accuracy:   {xgb_train_acc:.4f}")
print(f"Validation Accuracy: {xgb_val_acc:.4f}")
print(f"Overfitting Gap:     {xgb_gap:.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, xgb_val_preds, target_names=['F','D','C','B','A']))

"""Step 3 - Hyperparameter Tuning (GridSearchCV)"""

print("\n" + "=" * 55)
print("       HYPERPARAMETER TUNING")
print("=" * 55)

# --- Random Forest Grid Search ---
rf_param_grid = {
    'n_estimators':     [100, 200, 300],
    'max_depth':        [8, 10, 12],
    'min_samples_split':[5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf_grid = GridSearchCV(
    estimator  = RandomForestClassifier(random_state=42),
    param_grid = rf_param_grid,
    cv         = 3,
    scoring    = 'accuracy',
    n_jobs     = -1,
    verbose    = 1
)

print("\nTuning Random Forest...")
rf_grid.fit(X_train_final, y_train_final)

print("\nBest Random Forest Parameters:")
print(rf_grid.best_params_)

# --- XGBoost Grid Search ---
xgb_param_grid = {
    'n_estimators':    [200, 300],
    'max_depth':       [4, 6],
    'learning_rate':   [0.05, 0.1],
    'subsample':       [0.7, 0.8],
    'colsample_bytree':[0.7, 0.8],
    'reg_alpha':       [0, 0.5],
    'reg_lambda':      [1, 2]
}

xgb_grid = GridSearchCV(
    estimator  = XGBClassifier(random_state=42, eval_metric='mlogloss'),
    param_grid = xgb_param_grid,
    cv         = 3,
    scoring    = 'accuracy',
    n_jobs     = -1,
    verbose    = 1
)

print("\nTuning XGBoost...")
xgb_grid.fit(X_train_final, y_train_final)

print("\nBest XGBoost Parameters:")
print(xgb_grid.best_params_)

"""Step 4 - Visualise Optimal Points"""

print("\n" + "=" * 55)
print("     OPTIMAL POINT VISUALISATION")
print("=" * 55)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('GridSearchCV: CV Score Distribution & Optimal Point',
             fontsize=14, fontweight='bold')

def plot_optimal_point(ax, grid, title, color):
    cv_results  = pd.DataFrame(grid.cv_results_)
    scores      = cv_results['mean_test_score'].values
    stds        = cv_results['std_test_score'].values
    best_idx    = np.argmin(cv_results['rank_test_score'].values)

    sorted_idx    = np.argsort(scores)
    sorted_scores = scores[sorted_idx]
    x_pos         = np.arange(len(sorted_scores))

    ax.plot(x_pos, sorted_scores, color=color, alpha=0.6,
            linewidth=1.2, label='CV Mean Accuracy')
    ax.fill_between(x_pos, sorted_scores, alpha=0.15, color=color)

    best_sorted_pos = np.where(sorted_idx == best_idx)[0][0]
    best_score      = scores[best_idx]
    best_std        = stds[best_idx]

    ax.scatter(best_sorted_pos, best_score, color='red', s=120, zorder=5,
               label=f'Optimal Point\nAcc = {best_score:.4f} ± {best_std:.4f}')
    ax.axhline(best_score, color='red', linestyle='--', linewidth=1, alpha=0.5)
    ax.annotate(f'  Best: {best_score:.4f}',
                xy=(best_sorted_pos, best_score),
                xytext=(best_sorted_pos + len(x_pos) * 0.05, best_score - 0.005),
                fontsize=10, color='red')

    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel('Parameter Combination (sorted by CV score)', fontsize=10)
    ax.set_ylabel('Mean CV Accuracy', fontsize=10)
    ax.legend(fontsize=10)
    ax.grid(axis='y', linestyle='--', alpha=0.4)

plot_optimal_point(axes[0], rf_grid,  'Random Forest — Optimal Point', 'steelblue')
plot_optimal_point(axes[1], xgb_grid, 'XGBoost — Optimal Point',       'darkorange')

plt.tight_layout()
plt.show()

# Optimal Point Summary
print("\n" + "=" * 60)
print("          OPTIMAL POINT SUMMARY (GridSearchCV)")
print("=" * 60)
for name, grid in [("Random Forest", rf_grid), ("XGBoost", xgb_grid)]:
    cv_df      = pd.DataFrame(grid.cv_results_)
    best_idx   = np.argmin(cv_df['rank_test_score'].values)
    best_score = grid.best_score_
    best_std   = cv_df['std_test_score'].values[best_idx]
    print(f"\n  {name}")
    print(f"    Best CV Accuracy : {best_score:.4f} ± {best_std:.4f}")
    print(f"    Best Parameters  :")
    for k, v in grid.best_params_.items():
        print(f"      {k:<25} = {v}")
print("\n" + "=" * 60)

"""Step 5 - Retrain Optimised Model and Evaluate"""

print("\n" + "=" * 55)
print("    OPTIMISED MODEL EVALUATION")
print("=" * 55)

# --- Optimised Random Forest ---
rf_optimised       = rf_grid.best_estimator_
rf_opt_train_preds = rf_optimised.predict(X_train_final)
rf_opt_val_preds   = rf_optimised.predict(X_val)
rf_opt_train_acc   = accuracy_score(y_train_final, rf_opt_train_preds)
rf_opt_val_acc     = accuracy_score(y_val, rf_opt_val_preds)

print("\n=== Optimised Random Forest ===")
print(f"Training Accuracy:   {rf_opt_train_acc:.4f}")
print(f"Validation Accuracy: {rf_opt_val_acc:.4f}")
print(f"Overfitting Gap:     {rf_opt_train_acc - rf_opt_val_acc:.4f}  (was {rf_gap:.4f})")
print("\nValidation Classification Report:")
print(classification_report(y_val, rf_opt_val_preds,
                             target_names=['F','D','C','B','A'],
                             zero_division=0))

# --- Optimised XGBoost (early_stopping_rounds in constructor for XGBoost >= 1.6) ---
best_xgb_params = xgb_grid.best_params_.copy()

xgb_final = XGBClassifier(
    **best_xgb_params,
    random_state          = 42,
    eval_metric           = 'mlogloss',
    early_stopping_rounds = 20,          # ← moved here from .fit()
)
xgb_final.fit(
    X_train_final, y_train_final,
    eval_set = [(X_val, y_val)],
    verbose  = False
)

xgb_opt_train_preds = xgb_final.predict(X_train_final)
xgb_opt_val_preds   = xgb_final.predict(X_val)
xgb_opt_train_acc   = accuracy_score(y_train_final, xgb_opt_train_preds)
xgb_opt_val_acc     = accuracy_score(y_val, xgb_opt_val_preds)

print("\n=== Optimised XGBoost ===")
print(f"Training Accuracy:   {xgb_opt_train_acc:.4f}")
print(f"Validation Accuracy: {xgb_opt_val_acc:.4f}")
print(f"Overfitting Gap:     {xgb_opt_train_acc - xgb_opt_val_acc:.4f}  (was {xgb_gap:.4f})")
print("\nValidation Classification Report:")
print(classification_report(y_val, xgb_opt_val_preds,
                             target_names=['F','D','C','B','A'],
                             zero_division=0))

"""Step 6 - Before vs After Comparison Plot"""

print("\n" + "=" * 55)
print("    BEFORE vs AFTER COMPARISON PLOT")
print("=" * 55)

models       = ['Random Forest', 'XGBoost']
train_before = [rf_train_acc,     xgb_train_acc]
val_before   = [rf_val_acc,       xgb_val_acc]
train_after  = [rf_opt_train_acc, xgb_opt_train_acc]
val_after    = [rf_opt_val_acc,   xgb_opt_val_acc]

x     = np.arange(len(models))
width = 0.2

fig, ax = plt.subplots(figsize=(12, 6))
bars1 = ax.bar(x - 1.5*width, train_before, width, label='Train (Before)', color='steelblue',  alpha=0.6)
bars2 = ax.bar(x - 0.5*width, val_before,   width, label='Val (Before)',   color='steelblue',  alpha=1.0)
bars3 = ax.bar(x + 0.5*width, train_after,  width, label='Train (After)',  color='darkorange', alpha=0.6)
bars4 = ax.bar(x + 1.5*width, val_after,    width, label='Val (After)',    color='darkorange', alpha=1.0)

ax.set_ylabel('Accuracy', fontsize=12)
ax.set_title('Model Optimisation: Before vs After Hyperparameter Tuning',
             fontsize=13, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(models, fontsize=13)
ax.set_ylim(0.5, 1.05)
ax.legend(fontsize=11)
ax.grid(axis='y', linestyle='--', alpha=0.5)

for bar_group in [bars1, bars2, bars3, bars4]:
    for rect in bar_group:
        ax.annotate(f'{rect.get_height():.3f}',
                    xy=(rect.get_x() + rect.get_width() / 2, rect.get_height()),
                    xytext=(0, 4), textcoords="offset points",
                    ha='center', fontsize=9)

plt.tight_layout()
plt.show()

"""Step 7 - Overfitting Reduction Summary"""

print("\n" + "=" * 55)
print("        OVERFITTING REDUCTION SUMMARY")
print("=" * 55)
print(f"{'Model':<20} {'Before Gap':>12} {'After Gap':>12} {'Improved?':>10}")
print("-" * 55)

rf_after_gap  = rf_opt_train_acc  - rf_opt_val_acc
xgb_after_gap = xgb_opt_train_acc - xgb_opt_val_acc

for model, before, after in [("Random Forest", rf_gap, rf_after_gap),
                               ("XGBoost",      xgb_gap, xgb_after_gap)]:
    improved = "✅ Yes" if after < before else "❌ No"
    print(f"{model:<20} {before:>12.4f} {after:>12.4f} {improved:>10}")

print("=" * 55)
print("\nConclusion: Hyperparameter tuning on the validation set")
print("successfully reduced the train-val accuracy gap, indicating")
print("improved generalisation and reduced overfitting.")

"""Handling Imbalance using SMOTE"""

pip install imbalanced-learn

from collections import Counter
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek
from sklearn.utils.class_weight import compute_sample_weight
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay


# -----VISUALISE CLASS DISTRIBUTION BEFORE ────────────────

class_labels  = ['F', 'D', 'C', 'B', 'A']
class_counts  = Counter(y_train_final)
sorted_counts = [class_counts[i] for i in range(len(class_labels))]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Class Distribution: Before vs After Resampling',
             fontsize=13, fontweight='bold')

colors = ['#e74c3c', '#e67e22', '#3498db', '#2ecc71', '#9b59b6']

axes[0].bar(class_labels, sorted_counts, color=colors, edgecolor='white', linewidth=0.8)
axes[0].set_title('Before Resampling', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Grade Class')
axes[0].set_ylabel('Sample Count')
axes[0].grid(axis='y', linestyle='--', alpha=0.5)
for i, v in enumerate(sorted_counts):
    axes[0].text(i, v + 5, str(v), ha='center', fontsize=11, fontweight='bold')

print("=" * 50)
print("   CLASS DISTRIBUTION — BEFORE RESAMPLING")
print("=" * 50)
for i, label in enumerate(class_labels):
    print(f"  Class {label}: {sorted_counts[i]:>5} samples")
print(f"  {'Total':<8}: {sum(sorted_counts):>5} samples")
print("=" * 50)


# — APPLY SMOTETomek (Oversample minority + clean majority) ──

# SMOTETomek = SMOTE oversampling + Tomek Links cleaning
# Better than plain SMOTE — removes borderline majority samples too
smote_tomek = SMOTETomek(random_state=42)
X_train_bal, y_train_bal = smote_tomek.fit_resample(X_train_final, y_train_final)

# Distribution after resampling
bal_counts        = Counter(y_train_bal)
sorted_bal_counts = [bal_counts[i] for i in range(len(class_labels))]

axes[1].bar(class_labels, sorted_bal_counts, color=colors, edgecolor='white', linewidth=0.8)
axes[1].set_title('After SMOTETomek Resampling', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Grade Class')
axes[1].set_ylabel('Sample Count')
axes[1].grid(axis='y', linestyle='--', alpha=0.5)
for i, v in enumerate(sorted_bal_counts):
    axes[1].text(i, v + 5, str(v), ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

print("\n" + "=" * 50)
print("   CLASS DISTRIBUTION — AFTER RESAMPLING")
print("=" * 50)
for i, label in enumerate(class_labels):
    print(f"  Class {label}: {sorted_bal_counts[i]:>5} samples")
print(f"  {'Total':<8}: {sum(sorted_bal_counts):>5} samples")
print("=" * 50)


# — RETRAIN MODELS ON BALANCED DATA ────────────────────

print("\n" + "=" * 55)
print("  RETRAINING ON BALANCED DATA")
print("=" * 55)

# --- Random Forest on balanced data ---
# Also add class_weight='balanced' as a second layer of protection
rf_balanced = RandomForestClassifier(
    **{k: v for k, v in rf_grid.best_params_.items()},
    class_weight = 'balanced',
    random_state = 42
)
rf_balanced.fit(X_train_bal, y_train_bal)

rf_bal_train_preds = rf_balanced.predict(X_train_bal)
rf_bal_val_preds   = rf_balanced.predict(X_val)
rf_bal_train_acc   = accuracy_score(y_train_bal, rf_bal_train_preds)
rf_bal_val_acc     = accuracy_score(y_val, rf_bal_val_preds)

print("\n=== Random Forest (Balanced) ===")
print(f"Training Accuracy:   {rf_bal_train_acc:.4f}")
print(f"Validation Accuracy: {rf_bal_val_acc:.4f}")
print(f"Overfitting Gap:     {rf_bal_train_acc - rf_bal_val_acc:.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, rf_bal_val_preds,
                             target_names=class_labels, zero_division=0))

# --- XGBoost on balanced data ---
# Use sample_weight (XGBoost multiclass doesn't support class_weight directly)
sample_weights = compute_sample_weight(class_weight='balanced', y=y_train_bal)

xgb_balanced = XGBClassifier(
    **{k: v for k, v in xgb_grid.best_params_.items()},
    random_state          = 42,
    eval_metric           = 'mlogloss',
    early_stopping_rounds = 20,
)
xgb_balanced.fit(
    X_train_bal, y_train_bal,
    sample_weight = sample_weights,
    eval_set      = [(X_val, y_val)],
    verbose       = False
)

xgb_bal_train_preds = xgb_balanced.predict(X_train_bal)
xgb_bal_val_preds   = xgb_balanced.predict(X_val)
xgb_bal_train_acc   = accuracy_score(y_train_bal, xgb_bal_train_preds)
xgb_bal_val_acc     = accuracy_score(y_val, xgb_bal_val_preds)

print("\n=== XGBoost (Balanced) ===")
print(f"Training Accuracy:   {xgb_bal_train_acc:.4f}")
print(f"Validation Accuracy: {xgb_bal_val_acc:.4f}")
print(f"Overfitting Gap:     {xgb_bal_train_acc - xgb_bal_val_acc:.4f}")
print("\nValidation Classification Report:")
print(classification_report(y_val, xgb_bal_val_preds,
                             target_names=class_labels, zero_division=0))


# — CONFUSION MATRICES ──────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Confusion Matrices — After Balancing (Validation Set)',
             fontsize=13, fontweight='bold')

for ax, preds, title in zip(
    axes,
    [rf_bal_val_preds, xgb_bal_val_preds],
    ['Random Forest (Balanced)', 'XGBoost (Balanced)']
):
    ConfusionMatrixDisplay.from_predictions(
        y_val, preds,
        display_labels = class_labels,
        cmap           = 'Blues',
        ax             = ax,
        colorbar       = False
    )
    ax.set_title(title, fontsize=12, fontweight='bold')

plt.tight_layout()
plt.show()


# — BEFORE vs AFTER BALANCING SUMMARY ──────────────────

print("\n" + "=" * 65)
print("        IMPACT OF CLASS BALANCING — FULL SUMMARY")
print("=" * 65)
print(f"{'Model':<20} {'Val Acc (Before)':>17} {'Val Acc (After)':>16} {'Change':>8}")
print("-" * 65)

for model, before, after in [
    ("Random Forest", rf_opt_val_acc,  rf_bal_val_acc),
    ("XGBoost",       xgb_opt_val_acc, xgb_bal_val_acc)
]:
    change  = after - before
    flag    = "✅" if change >= 0 else "⚠️"
    print(f"{model:<20} {before:>17.4f} {after:>16.4f} {flag} {change:>+.4f}")

print("=" * 65)
print("\nNote: Overall accuracy may dip slightly — this is expected.")
print("The key gain is in minority class recall (especially F and A).")
print("Check per-class F1 scores in the classification reports above.")

"""Milestone 5

Step 1 — Final Test Set Evaluation
"""

from sklearn.metrics import (accuracy_score, classification_report,
                              ConfusionMatrixDisplay, roc_auc_score)
import matplotlib.pyplot as plt
import numpy as np

class_labels = ['F', 'D', 'C', 'B', 'A']

print("=" * 60)
print("   MILESTONE 5: FINAL EVALUATION ON TEST SET")
print("=" * 60)

# --- Random Forest Final Test Evaluation ---
rf_test_preds = rf_balanced.predict(X_test)
rf_test_acc   = accuracy_score(y_test, rf_test_preds)

print("\n=== Random Forest — Final Test Results ===")
print(f"Test Accuracy: {rf_test_acc:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, rf_test_preds,
                             target_names=class_labels, zero_division=0))

# --- XGBoost Final Test Evaluation ---
xgb_test_preds = xgb_balanced.predict(X_test)
xgb_test_acc   = accuracy_score(y_test, xgb_test_preds)

print("\n=== XGBoost — Final Test Results ===")
print(f"Test Accuracy: {xgb_test_acc:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, xgb_test_preds,
                             target_names=class_labels, zero_division=0))

"""Step 2 — Confusion Matrices (Test Set)"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Confusion Matrices — Final Test Set Evaluation',
             fontsize=13, fontweight='bold')

for ax, preds, title in zip(
    axes,
    [rf_test_preds, xgb_test_preds],
    ['Random Forest (Test)', 'XGBoost (Test)']
):
    ConfusionMatrixDisplay.from_predictions(
        y_test, preds,
        display_labels=class_labels,
        cmap='Blues', ax=ax, colorbar=False
    )
    ax.set_title(title, fontsize=12, fontweight='bold')

plt.tight_layout()
plt.show()

"""Step 3 — Train → Validation → Test Accuracy Progression"""

stages  = ['Training', 'Validation', 'Test']
rf_accs  = [rf_bal_train_acc, rf_bal_val_acc,  rf_test_acc]
xgb_accs = [xgb_bal_train_acc, xgb_bal_val_acc, xgb_test_acc]

x = np.arange(len(stages))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))
ax.bar(x - width/2, rf_accs,  width, label='Random Forest', color='steelblue')
ax.bar(x + width/2, xgb_accs, width, label='XGBoost',       color='darkorange')

ax.set_ylabel('Accuracy', fontsize=12)
ax.set_title('Train → Validation → Test Accuracy Progression',
             fontsize=13, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(stages, fontsize=12)
ax.set_ylim(0.5, 1.05)
ax.legend(fontsize=11)
ax.grid(axis='y', linestyle='--', alpha=0.5)

for bar_group in ax.containers:
    ax.bar_label(bar_group, fmt='%.3f', padding=3, fontsize=10)

plt.tight_layout()
plt.show()

"""Step 4 — Error Analysis"""

import pandas as pd

# Use the better-performing model (adjust if RF wins)
best_preds = xgb_test_preds   # swap to rf_test_preds if RF is better

errors      = y_test != best_preds
error_df    = X_test[errors].copy()
error_df['True_Grade']      = y_test[errors].values
error_df['Predicted_Grade'] = best_preds[errors]
error_df['True_Label']      = error_df['True_Grade'].map(
    {0:'F', 1:'D', 2:'C', 3:'B', 4:'A'})
error_df['Pred_Label']      = error_df['Predicted_Grade'].map(
    {0:'F', 1:'D', 2:'C', 3:'B', 4:'A'})

print(f"\nTotal misclassifications: {errors.sum()} / {len(y_test)}")
print("\nMost common error patterns (True → Predicted):")
print(error_df.groupby(['True_Label','Pred_Label']).size()
      .reset_index(name='Count')
      .sort_values('Count', ascending=False).head(10))

"""Step 5 — Final Summary"""

print("\n" + "=" * 60)
print("           FINAL MODEL COMPARISON SUMMARY")
print("=" * 60)
print(f"{'Metric':<25} {'Random Forest':>15} {'XGBoost':>15}")
print("-" * 60)
print(f"{'Test Accuracy':<25} {rf_test_acc:>15.4f} {xgb_test_acc:>15.4f}")
print(f"{'Val Accuracy':<25} {rf_bal_val_acc:>15.4f} {xgb_bal_val_acc:>15.4f}")
print(f"{'Train-Test Gap':<25} {rf_bal_train_acc-rf_test_acc:>15.4f} {xgb_bal_train_acc-xgb_test_acc:>15.4f}")
print("=" * 60)

winner = "Random Forest" if rf_test_acc >= xgb_test_acc else "XGBoost"
print(f"\n✅ Best Model: {winner}")
print("\nConclusion:")
print("  - Final evaluation on the unseen test set confirms the model")
print("    generalises well beyond the training/validation data.")
print("  - Remaining errors are mostly 1-grade misclassifications")
print("    (e.g., B predicted as A), which are near-boundary cases.")
print("  - Future work: feature engineering on study habits,")
print("    ensemble stacking, or deep learning on larger datasets.")